
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 12 10:46:57 CET 2017
//----------------------------------------------------

package toucan.analyse;

/** CUP generated class containing symbol constants. */
public class CodeLexicaux {
  /* terminals */
  public static final int IDF = 7;
  public static final int CROFER = 4;
  public static final int POINTVIRGULE = 2;
  public static final int CSTE = 8;
  public static final int EOF = 0;
  public static final int TYPEPRIMITIF = 6;
  public static final int CROOUV = 3;
  public static final int EGAL = 5;
  public static final int error = 1;
  public static final int TAB = 9;
}

